"""baseline

Revision ID: 74a39211f4f7
Revises: 
Create Date: 2026-05-23 15:48:22.536186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a39211f4f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('related_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('folder_path', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_path')
    )
    op.create_table('setlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('tempo_bpm', sa.Integer(), nullable=True),
    sa.Column('tuning', sa.String(), nullable=True),
    sa.Column('vibe', sa.String(), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('reference_audio_file_id', sa.Integer(), nullable=True),
    sa.Column('promoted_from_id', sa.Integer(), nullable=True),
    sa.Column('rating_overall', sa.Integer(), nullable=True),
    sa.Column('rating_vocals', sa.Integer(), nullable=True),
    sa.Column('rating_guitar', sa.Integer(), nullable=True),
    sa.Column('rating_drums', sa.Integer(), nullable=True),
    sa.Column('rating_tone', sa.Integer(), nullable=True),
    sa.Column('rating_timing', sa.Integer(), nullable=True),
    sa.Column('rating_energy', sa.Integer(), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.Column('times_practiced', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['promoted_from_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['reference_audio_file_id'], ['audio_files.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_predefined', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audio_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('submitted_file_name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_stem', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('clip_name', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('rating_overall', sa.Float(), nullable=True),
    sa.Column('rating_vocals', sa.Float(), nullable=True),
    sa.Column('rating_guitar', sa.Float(), nullable=True),
    sa.Column('rating_drums', sa.Float(), nullable=True),
    sa.Column('rating_tone', sa.Float(), nullable=True),
    sa.Column('rating_timing', sa.Float(), nullable=True),
    sa.Column('rating_energy', sa.Float(), nullable=True),
    sa.Column('rating_keys', sa.Float(), nullable=True),
    sa.Column('rating_bass', sa.Float(), nullable=True),
    sa.Column('rating_mix', sa.Float(), nullable=True),
    sa.Column('rating_other', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('lyrics_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('lyrics_text', sa.Text(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['setlist_id'], ['setlists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_tabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('instrument', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_tags',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'tag_id')
    )
    op.create_table('takes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('clip_name', sa.String(), nullable=False),
    sa.Column('source_video', sa.String(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('rating_overall', sa.Integer(), nullable=True),
    sa.Column('rating_vocals', sa.Integer(), nullable=True),
    sa.Column('rating_guitar', sa.Integer(), nullable=True),
    sa.Column('rating_drums', sa.Integer(), nullable=True),
    sa.Column('rating_tone', sa.Integer(), nullable=True),
    sa.Column('rating_timing', sa.Integer(), nullable=True),
    sa.Column('rating_energy', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_file_tags',
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audio_file_id', 'tag_id')
    )
    op.create_table('take_tags',
    sa.Column('take_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['take_id'], ['takes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('take_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('take_tags')
    op.drop_table('audio_file_tags')
    op.drop_table('takes')
    op.drop_table('song_tags')
    op.drop_table('song_tabs')
    op.drop_table('setlist_items')
    op.drop_table('lyrics_versions')
    op.drop_table('audio_files')
    op.drop_table('tags')
    op.drop_table('songs')
    op.drop_table('setlists')
    op.drop_table('practice_sessions')
    op.drop_table('options')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
